# Site settings
port: 4000
title: joonsrenderer gem for JRubyArt and propane
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
  The joonsrenderer gem is wrapper around the joonsrenderer library by Joon HyubLee that makes it very easy to sunflow raytracing of JRubyArt and propane sketches.
baseurl: "" # the subpath of your site, e.g. /blog
regenerate: true
url: "https://ruby-processing.github.io/joonsrenderer"

urls:
  bugs: https://github.com/ruby-processing/joonsrenderer/issues/
  github: https://github.com/ruby-processing/joonsrenderer/
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true
# Build settings
markdown: kramdown
